// Dados do checklist Check Imóvel — extraídos e adaptados do PDF-fonte do projeto.
// appliesTo: 'all' | 'house' | 'apartment' — informativo, útil para uma futura filtragem.

export type Severity = "critico" | "importante" | "atencao";

export type Category = "compra" | "manutencao" | "construcao";

export interface ChecklistItemData {
  id: string;
  title: string;
  description?: string;
  severity?: Severity;
  group?: string;
}

export interface ChecklistSectionData {
  id: string;
  title: string;
  subtitle: string;
  appliesTo: "all" | "house" | "apartment";
  category: Category;
  items: ChecklistItemData[];
}

export const sections: ChecklistSectionData[] = [
  {
    id: "geral",
    title: "Geral",
    subtitle: "Vale para qualquer imóvel — casa ou apartamento.",
    appliesTo: "all",
    category: "compra",
    items: [
      { id: "g1", title: "Visitar em dias e horários diferentes", description: "Idealmente dia útil de manhã, fim de tarde/noite e, se possível, fim de semana. Uma rua tranquila às 14h pode virar corredor de ônibus às 18h." },
      { id: "g2", title: "Visitar depois de uma chuva forte", description: "Uma das melhores inspeções gratuitas: revela infiltrações, manchas, cheiro de umidade e problemas de drenagem.", severity: "importante" },
      { id: "g3", title: "Observar em quais cômodos entra sol e por quanto tempo", description: 'Não confiar apenas no que o corretor descreve como "sol da manhã/tarde" — o entorno construído pode bloquear a insolação.' },
      { id: "g4", title: "Verificar se existe ventilação cruzada", description: "Se todas as janelas forem viradas para o mesmo lado, não há ventilação cruzada." },
      { id: "g5", title: "Visitar à noite também", description: "É quando fica mais silencioso — dá para avaliar o isolamento acústico real do imóvel." },
      { id: "g6", title: "Ficar alguns minutos em silêncio absoluto e escutar", description: "Elevador, bombas, trânsito, vizinhos, cachorro, portão, bares, escola, igreja, oficina.", severity: "importante" },
      { id: "g7", title: "Testar o sinal de celular dentro do imóvel", description: "Principalmente em quartos e escritório — algumas operadoras somem dentro de certas construções." },
      { id: "g8", title: "Descobrir quais provedores de internet realmente atendem o endereço", description: '"Tem fibra no bairro" não significa que há porta disponível naquele prédio ou rua.' },
      { id: "g9", title: "Medir os ambientes de verdade", description: "Levar trena ou medidor a laser e simular cama, sofá, mesa, geladeira e abertura de portas — a planta humanizada engana." },
      { id: "g10", title: "Simular a rotina, não só a visita", description: "Onde guarda compras, seca roupa, guarda aspirador, joga lixo, trabalha, deixa sapatos, recebe entregas." },
      { id: "g11", title: "Pesquisar a rua, não apenas o imóvel", description: "Alagamento, segurança, ruído, trânsito, feira, bares, escolas, hospitais, estádios e obras previstas." },
      { id: "g12", title: "Conversar com porteiro, zelador ou moradores", description: '"Tem algum problema recorrente aqui?" costuma render informações que o anúncio não traz.', severity: "importante" },
      { id: "g13", title: "Contratar um despachante, se a imobiliária oferecer", description: "Facilita bastante a parte documental da compra." },
    ],
  },
  {
    id: "vistoria",
    title: "Vistoria",
    subtitle: "Um roteiro prático para seguir durante a visita.",
    appliesTo: "all",
    category: "compra",
    items: [
      { id: "v1", group: "Estrutura", title: "Procurar trincas diagonais nos cantos de portas e janelas", description: "Fissura fina pode ser só revestimento; trincas largas ou recorrentes merecem avaliação de engenheiro.", severity: "critico" },
      { id: "v2", group: "Estrutura", title: "Verificar pisos desnivelados, portas ou janelas desalinhadas", description: "Portas que fecham sozinhas ou não encaixam, janelas deformadas.", severity: "importante" },
      { id: "v3", group: "Estrutura", title: "Procurar manchas de infiltração, bolhas na pintura, rodapés estufados", description: "Rejunte escurecido e cheiro de mofo também são sinais." },
      { id: "v4", group: "Estrutura", title: "Checar se reformas anteriores removeram paredes", description: "Em caso de dúvida, pedir o projeto ou laudo estrutural.", severity: "importante" },
      { id: "v5", group: "Hidráulica", title: "Abrir todas as torneiras e testar chuveiros e descargas ao mesmo tempo", description: "Observar pressão, demora para escoar e ruídos na tubulação — pressão ruim em certos andares pode ser dor de cabeça.", severity: "importante" },
      { id: "v6", group: "Hidráulica", title: "Procurar vazamentos em sifões, registros e embaixo das pias", description: "" },
      { id: "v7", group: "Hidráulica", title: 'Verificar se o vaso sanitário fica "correndo" e se há retorno de água', description: "" },
      { id: "v8", group: "Hidráulica", title: "Procurar cheiro de esgoto nos ralos", description: "" },
      { id: "v9", group: "Elétrica", title: "Abrir o quadro elétrico e verificar circuitos, DR e aterramento", description: "Checar identificação dos disjuntores e o estado aparente da instalação.", severity: "importante" },
      { id: "v10", group: "Elétrica", title: "Confirmar bitola adequada para chuveiro/ar-condicionado e tensão disponível", description: "127V, 220V e carga disponibilizada para a unidade." },
      { id: "v11", group: "Elétrica", title: "Verificar se há circuitos independentes para equipamentos de grande potência", description: "" },
      { id: "v12", group: "Portas e janelas", title: "Testar abertura e fechamento de todas as portas e janelas", description: "Ver fechaduras, testar persianas, procurar frestas e sinais de infiltração nas esquadrias." },
      { id: "v13", group: "Portas e janelas", title: "Verificar vidros trincados e esquadrias desalinhadas", description: "" },
      { id: "v14", group: "Umidade e infiltração", title: "Olhar para cima em banheiro, cozinha, lavanderia e cantos de janela", description: "Pintura nova localizada pode ser manutenção — ou pode estar escondendo infiltração.", severity: "importante" },
      { id: "v15", group: "Umidade e infiltração", title: "Cheirar o imóvel", description: "Cheiro forte de tinta, aromatizador ou produto de limpeza pode mascarar mofo, esgoto ou cigarro." },
      { id: "v16", group: "Gás", title: "Verificar se há gás encanado ou GLP e o estado das conexões", description: "Localizar onde fica o registro de gás." },
      { id: "v17", group: "Gás", title: "Se houver aquecedor, checar instalação, ventilação/exaustão e manutenção", description: "Confirmar se ele atende, ao mesmo tempo, todos os pontos que pretende usar.", severity: "importante" },
      { id: "v18", group: "Pisos e acabamentos", title: "Procurar pisos ocos ou soltos e rejuntes comprometidos", description: "Verificar pedras de pia rachadas, bancadas e descolamento de revestimentos." },
      { id: "v19", group: "Sol, ventilação e conexões", title: "Ver em quais cômodos entra sol e por quanto tempo, de fato", description: "" },
      { id: "v20", group: "Sol, ventilação e conexões", title: "Pensar onde ficarão as condensadoras de ar-condicionado", description: "Regras de condomínio, distância entre evaporadora/condensadora ou falta de local técnico podem virar um pesadelo.", severity: "importante" },
    ],
  },
  {
    id: "apartamento",
    title: "Apartamento",
    subtitle: "Pontos específicos de unidades em condomínio.",
    appliesTo: "apartment",
    category: "compra",
    items: [
      { id: "a1", title: "Estudar a planta do bloco, não só da unidade", description: "Você terá vizinhos em cima e embaixo — vale saber o que ficará colado à parede do seu quarto." },
      { id: "a2", title: "Evitar unidades viradas para piscina, quadra ou área de lazer", description: "A menos que barulho e movimento não sejam um problema para você.", severity: "importante" },
      { id: "a3", title: "Considerar cheiro de fumaça/combustível em unidades sobre estacionamento", description: "Especialmente dormindo com janela aberta em andares baixos." },
      { id: "a4", title: "Descobrir onde ficam elevadores, casa de máquinas, bombas, gerador, lixeira e portões", description: "Unidades próximas podem ouvir funcionamento e conversas o dia todo.", severity: "importante" },
      { id: "a5", title: "Evitar o primeiro andar habitável sobre áreas comuns", description: "Academia, salão de festas, garagem e portaria embaixo podem ser piores que um vizinho residencial.", severity: "importante" },
      { id: "a6", title: "Investigar a impermeabilização da cobertura no último andar", description: "Você elimina o vizinho de cima, mas problemas de impermeabilização da laje aparecem justamente ali.", severity: "critico" },
      { id: "a7", title: "Verificar por onde passa a prumada hidráulica", description: "Tubulações e descargas de outras unidades podem gerar ruído durante a noite." },
      { id: "a8", title: "Checar o número de elevadores em relação ao número de unidades", description: "Poucos elevadores para um prédio grande complicam horários de pico e mudanças." },
      { id: "a9", title: "Entender se a água é individualizada ou coletiva", description: "Verificar reservatórios, histórico de falta e como é feita a cobrança." },
      { id: "a10", title: "Entender a vaga de garagem", description: "Determinada ou rotativa? Presa? Matrícula própria? Cabe carro grande? Depende do vizinho para sair?", severity: "importante" },
      { id: "a11", title: "Investigar a possibilidade de carregamento para carro elétrico", description: "Não presumir que basta instalar uma tomada na vaga." },
      { id: "a12", title: "Ler o memorial descritivo e o contrato antes de assinar", description: "É onde aparecem detalhes como gás para chuveiro (proíbe elétrico) ou instalação só para fogão.", severity: "importante" },
      { id: "a13", title: "Pedir e ler o regimento interno", description: "Se não concordar com alguma regra ali, reconsiderar a compra.", severity: "importante" },
      { id: "a14", title: "Pedir as atas das últimas assembleias — não só o regimento", description: "Revelam infiltrações recorrentes, brigas judiciais, inadimplência, obras caras previstas e reclamações.", severity: "critico" },
      { id: "a15", title: "Pedir informações financeiras do condomínio", description: "Fundo de reserva, inadimplência, obras aprovadas e chamadas extras previstas.", severity: "critico" },
      { id: "a16", title: "Perguntar sobre obras grandes já feitas e as próximas previstas", description: "Fachada, impermeabilização, telhado, elevadores, elétrica, hidráulica, caixa-d’água." },
      { id: "a17", title: "Desconfiar de condomínio barato demais", description: "Pode ser estrutura eficiente — ou manutenção postergada." },
      { id: "a18", title: "Confirmar regras de reforma antes de comprar", description: "Derrubar uma parede pode não ser possível por questões estruturais, hidráulicas ou de fachada.", severity: "importante" },
      { id: "a19", title: "Verificar o padrão da fachada antes de contar com mudanças", description: "Fechar varanda, instalar rede, envidraçar ou colocar condensadora depende das regras do prédio." },
    ],
  },
  {
    id: "casa",
    title: "Casa",
    subtitle: "Pontos específicos de imóveis com terreno próprio.",
    appliesTo: "house",
    category: "compra",
    items: [
      { id: "c1", title: "Descobrir para onde vai a água do terreno quando chove", description: "Água convergindo para a casa é um péssimo sinal.", severity: "critico" },
      { id: "c2", title: "Comparar o nível entre casa, quintal, calçada e rua", description: "Casa abaixo do nível da rua merece investigação cuidadosa sobre drenagem e histórico de alagamento.", severity: "importante" },
      { id: "c3", title: "Procurar fissuras e trincas", description: "Trincas diagonais, recorrentes, largas ou próximas a portas/janelas merecem avaliação profissional.", severity: "critico" },
      { id: "c4", title: "Observar muros de arrimo em terrenos inclinados", description: "Podem envolver estruturas caras e críticas que ninguém considera numa visita rápida.", severity: "importante" },
      { id: "c5", title: "Observar terrenos vizinhos mais altos", description: "A casa pode parecer seca no verão e receber água de terrenos vizinhos durante chuvas." },
      { id: "c6", title: "Checar telhado e calhas", description: "Telha quebrada, estrutura deteriorada, calha entupida ou rufos ruins são fontes clássicas de infiltração." },
      { id: "c7", title: "Procurar sinais de cupim", description: "Batentes, rodapés, telhado, armários embutidos e estruturas de madeira.", severity: "importante" },
      { id: "c8", title: "Observar umidade ascendente nas paredes perto do piso", description: "Pode indicar problema na impermeabilização da fundação/baldrame — não se resolve só pintando.", severity: "importante" },
      { id: "c9", title: "Descobrir para onde vai o esgoto", description: "Rede pública ou fossa? Em imóveis antigos isso é especialmente importante." },
      { id: "c10", title: "Verificar estado e capacidade da caixa-d’água", description: "Acesso para limpeza e existência de vazamentos." },
      { id: "c11", title: "Descobrir a idade aproximada das instalações hidráulicas", description: "Tubulações antigas podem significar reforma bastante invasiva." },
      { id: "c12", title: "Avaliar árvores grandes perto da casa", description: "Ótimas para conforto térmico, mas raízes, folhas nas calhas e risco de queda entram na conta." },
      { id: "c13", title: "Considerar construções futuras dos vizinhos", description: "Uma janela ótima hoje pode perder iluminação com uma construção vizinha de vários pavimentos." },
      { id: "c14", title: "Pesquisar o zoneamento da região", description: "Aquela casinha tranquila ao lado pode legalmente virar prédio ou comércio no futuro.", severity: "importante" },
      { id: "c15", title: 'Avaliar a segurança além do "bairro"', description: "Muros escaláveis, terrenos baldios, vielas, iluminação pública, acesso lateral e pontos cegos." },
      { id: "c16", title: "Em sobrado, avaliar as escadas pensando em 10–20 anos", description: "Idosos, crianças e lesões podem transformar uma planta boa hoje em problema depois." },
      { id: "c17", title: "Confirmar os limites reais do terreno", description: "Muro existente não é garantia de que esteja exatamente sobre a divisa jurídica.", severity: "importante" },
    ],
  },
  {
    id: "manutencao",
    title: "Manutenção",
    subtitle: "O que planejar e orçar ao longo do tempo.",
    appliesTo: "all",
    category: "manutencao",
    items: [
      { id: "m1", group: "Curto prazo — primeiros 12 meses", title: "Trocar fechaduras e revisar chaves de todas as portas", description: "" },
      { id: "m2", group: "Curto prazo — primeiros 12 meses", title: "Fazer revisão elétrica e hidráulica completa", description: "Provavelmente o período em que você mais vai gastar.", severity: "importante" },
      { id: "m3", group: "Curto prazo — primeiros 12 meses", title: "Limpar/revisar caixa-d’água, ar-condicionado e aquecedor a gás", description: "" },
      { id: "m4", group: "Curto prazo — primeiros 12 meses", title: "Contratar dedetização e limpar calhas (em casas)", description: "" },
      { id: "m5", group: "Curto prazo — primeiros 12 meses", title: "Corrigir infiltrações, rejuntes e silicones identificados na vistoria", description: "" },
      { id: "m6", group: "Curto prazo — primeiros 12 meses", title: "Fazer reparos e limpeza profunda antes da mudança", description: "Torneiras/registros problemáticos, tomadas, revisão do telhado." },
      { id: "m7", group: "Médio prazo — 1 a 5 anos", title: "Repintar ambientes internos e, em casas, a fachada externa", description: "" },
      { id: "m8", group: "Médio prazo — 1 a 5 anos", title: "Revisar esquadrias, impermeabilização pontual e vedantes/rejuntes", description: "" },
      { id: "m9", group: "Médio prazo — 1 a 5 anos", title: "Revisar telhado, calhas e instalações hidráulicas", description: "" },
      { id: "m10", group: "Médio prazo — 1 a 5 anos", title: "Fazer manutenção preventiva de ar-condicionado e aquecedor", description: "No apartamento, parte disso é do condomínio — mas paga-se coletivamente. As atas das assembleias importam." },
      { id: "m11", group: "Médio prazo — 1 a 5 anos", title: "Tratar madeira contra cupim quando necessário", description: "" },
      { id: "m12", group: "Longo prazo — 5 a 15+ anos", title: "Planejar impermeabilização geral, troca de telhado e esquadrias", description: "", severity: "importante" },
      { id: "m13", group: "Longo prazo — 5 a 15+ anos", title: "Reservar orçamento para reforma de banheiro e cozinha", description: "" },
      { id: "m14", group: "Longo prazo — 5 a 15+ anos", title: "Planejar reforma hidráulica e modernização elétrica completas", description: "" },
      { id: "m15", group: "Longo prazo — 5 a 15+ anos", title: "Prever troca de pisos, correção de fachada e troca de equipamentos antigos", description: "" },
      { id: "m16", group: "Longo prazo — 5 a 15+ anos", title: "Em condomínio: acompanhar modernização de elevadores e impermeabilização da cobertura", description: "Também garagem, bombas, prumadas, reservatórios, portões e sistemas de segurança." },
    ],
  },
  {
    id: "custos-compra",
    title: "Custos da compra",
    subtitle: "O preço anunciado não é o custo total.",
    appliesTo: "all",
    category: "compra",
    items: [
      { id: "cc1", title: "Verificar se o orçamento inclui o ITBI", description: "Além do valor de entrada e do financiamento.", severity: "critico" },
      { id: "cc2", title: "Verificar a necessidade de escritura pública", description: "O instrumento do financiamento pode ter efeito equivalente em algumas operações — não somar automaticamente." },
      { id: "cc3", title: "Orçar registro imobiliário e certidões/documentação", description: "" },
      { id: "cc4", title: "Orçar avaliação bancária e tarifas do financiamento", description: "" },
      { id: "cc5", title: "Considerar despachante, mudança e reparos/reformas iniciais", description: "" },
      { id: "cc6", title: "Considerar móveis e eletrodomésticos no orçamento total", description: "" },
      { id: "cc7", title: "Confirmar a alíquota vigente do ITBI direto na Prefeitura", description: "Especialmente relevante para operações em São Paulo — a regra vale no momento da compra." },
    ],
  },
  {
    id: "custos-recorrentes",
    title: "Custos recorrentes",
    subtitle: "O que continua existindo depois da compra.",
    appliesTo: "all",
    category: "compra",
    items: [
      { id: "cr1", title: "Somar o custo mensal real do apartamento", description: "Financiamento + condomínio + IPTU + seguro + água + energia + gás + manutenção + eventuais rateios." },
      { id: "cr2", title: "Somar o custo mensal real da casa", description: "Financiamento + IPTU + seguro + água + energia + gás + manutenção + segurança + manutenção externa." },
      { id: "cr3", title: 'Lembrar que, na casa, você é o "condomínio"', description: "Portão, telhado, fachada, bomba e jardim ficam inteiramente por sua conta." },
      { id: "cr4", title: "Pedir o boleto real do condomínio e do IPTU", description: "Não aceitar apenas um valor estimado de boca.", severity: "importante" },
      { id: "cr5", title: "Verificar o que está incluído no condomínio", description: "R$ 700 com água e gás incluídos pode ser melhor que R$ 500 sem nada." },
      { id: "cr6", title: "Checar fundo de reserva, rateios extraordinários e inadimplência", description: "Também obras aprovadas e processos judiciais relevantes.", severity: "critico" },
      { id: "cr7", title: "Confirmar a situação de débitos do imóvel", description: "Antes de fechar negócio.", severity: "critico" },
    ],
  },
  {
    id: "financiamento",
    title: "Financiamento",
    subtitle: "Olhar além do valor da parcela.",
    appliesTo: "all",
    category: "compra",
    items: [
      { id: "f1", title: "Comparar a taxa de juros e o CET (Custo Efetivo Total)", description: "Duas propostas com parcelas parecidas podem ter custos totais bem diferentes.", severity: "importante" },
      { id: "f2", title: "Comparar sistema de amortização, prazo e seguros embutidos", description: "" },
      { id: "f3", title: "Verificar indexador, quando houver, e condições de amortização antecipada", description: "" },
      { id: "f4", title: "Não usar o limite máximo aprovado pelo banco como orçamento saudável", description: "O banco calcula capacidade de crédito — não sabe quanto você quer gastar com o resto da vida.", severity: "critico" },
      { id: "f5", title: "Montar uma reserva financeira específica para manutenção do imóvel", description: "Além da reserva de emergência pessoal. Em casa, essa reserva é ainda mais importante.", severity: "importante" },
    ],
  },
  {
    id: "ferramentas",
    title: "Ferramentas",
    subtitle: "Recursos gratuitos para estudar o terreno antes de decidir.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs1", title: "Shadow Map", description: "Use para simular a incidência solar no terreno e na futura casa em diferentes horários e épocas do ano. Não olhe apenas onde nasce e se põe o sol: veja quais fachadas, quartos, salas e áreas externas receberão sol e por quanto tempo." },
      { id: "cs2", title: "Google Maps / Street View", description: "Veja o histórico e o entorno do terreno, acessos, construções vizinhas e mudanças recentes na região." },
      { id: "cs3", title: "Google Earth", description: "Ajuda a entender relevo, ocupação do entorno, construções vizinhas e características gerais do terreno." },
    ],
  },
  {
    id: "antes-comprar-terreno",
    title: "Antes de comprar o terreno",
    subtitle: "Verificações que evitam comprar um problema caro disfarçado de terreno barato.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs4", title: "Consulte o zoneamento e as regras de uso e ocupação do solo antes de comprar", description: "O fato de existir uma casa que você gostaria de construir não significa que ela possa ser construída naquele terreno." },
      { id: "cs5", title: "Descubra os recuos obrigatórios, taxa de ocupação, coeficiente de aproveitamento, gabarito/altura máxima e taxa de permeabilidade" },
      { id: "cs6", title: "Verifique se existem servidões, faixas não edificáveis, restrições ambientais ou outras limitações sobre o terreno" },
      { id: "cs7", title: "Consulte a matrícula atualizada e confirme medidas, confrontações e área real do terreno" },
      { id: "cs8", title: "Não presuma que os muros existentes correspondem exatamente às divisas legais" },
      { id: "cs9", title: "Confira se há água, esgoto, energia elétrica, internet e drenagem pública disponíveis" },
      { id: "cs10", title: "Descubra onde fica a rede de esgoto e se será possível fazer a ligação por gravidade", description: "Dependendo do terreno, isso pode virar um problema caro." },
      { id: "cs11", title: "Investigue histórico de alagamentos da rua e dos terrenos próximos" },
      { id: "cs12", title: "Visite o terreno depois de chuva forte" },
      { id: "cs13", title: "Observe de onde vem e para onde vai a água", description: "Terrenos vizinhos mais altos podem jogar muita água para dentro do seu terreno." },
      { id: "cs14", title: "Veja a diferença de nível entre rua, calçada e terreno" },
      { id: "cs15", title: "Terreno muito abaixo da rua merece atenção especial" },
      { id: "cs16", title: "Terreno muito inclinado não é necessariamente ruim", description: "Mas pode aumentar bastante o custo com fundações, movimentação de terra e muros de arrimo." },
      { id: "cs17", title: "Não compare terrenos apenas pelo preço por metro quadrado", description: "Um terreno barato que exige R$ 100 mil adicionais de contenção, terraplenagem e fundação pode ser mais caro que outro aparentemente pior negócio." },
      { id: "cs18", title: "Se houver inclinação relevante, considere uma avaliação topográfica antes da compra" },
      { id: "cs19", title: "Observe árvores grandes, cursos d'água, pedras, aterros e sinais de movimentação de terra anterior" },
      { id: "cs20", title: "Converse com vizinhos", description: "Pergunte sobre alagamentos, falta d'água, quedas de energia, segurança, barulho e problemas conhecidos do solo ou da rua." },
    ],
  },
  {
    id: "sol-orientacao",
    title: "Sol e orientação da casa",
    subtitle: "Estude a insolação antes de fechar a implantação e a planta.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs21", title: "Use o Shadow Map antes de definir a implantação da casa" },
      { id: "cs22", title: "Simule diferentes épocas do ano", description: "A posição e a altura do sol mudam bastante entre verão e inverno." },
      { id: "cs23", title: 'Não pense apenas em "face norte" ou "sol da manhã"', description: "Analise cada ambiente individualmente." },
      { id: "cs24", title: "Pense onde você gostaria de ter sol pela manhã", description: "Quartos, cozinha, varanda etc." },
      { id: "cs25", title: "Pense onde o sol forte da tarde pode se tornar desagradável" },
      { id: "cs26", title: "Analise a posição das futuras janelas antes de fechar a planta" },
      { id: "cs27", title: "Considere os prédios, casas, muros e árvores existentes que podem bloquear o sol" },
      { id: "cs28", title: "Pense também no que poderá ser construído nos terrenos vizinhos", description: "Uma casa ensolarada hoje pode perder boa parte da insolação depois." },
      { id: "cs29", title: "Pense no conforto térmico antes de depender de ar-condicionado para corrigir um projeto ruim" },
      { id: "cs30", title: "Planeje beirais, brises, pergolados, vegetação e outros elementos de sombreamento onde fizer sentido" },
    ],
  },
  {
    id: "ventilacao",
    title: "Ventilação",
    subtitle: "Pense no caminho do ar, não só na iluminação.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs31", title: "Não projete apenas pensando em iluminação", description: "Pense também no caminho que o ar fará dentro da casa." },
      { id: "cs32", title: "Sempre que possível, tenha aberturas em fachadas diferentes para favorecer ventilação cruzada" },
      { id: "cs33", title: "Evite ambientes cuja única abertura dependa de corredor estreito e fechado entre a casa e o muro" },
      { id: "cs34", title: "Pense especialmente na ventilação de banheiros, cozinha e lavanderia" },
      { id: "cs35", title: "Considere como muros e construções vizinhas interferirão na circulação do ar" },
      { id: "cs36", title: "Não dependa exclusivamente de ventilação mecânica para resolver algo que poderia ter sido resolvido na implantação da casa" },
    ],
  },
  {
    id: "antes-fazer-planta",
    title: "Antes de fazer a planta",
    subtitle: "Levantamentos, sondagem, orçamento e responsáveis técnicos antes de desenhar.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs37", title: "Faça um levantamento topográfico adequado do terreno" },
      { id: "cs38", title: "Dependendo do terreno e da obra, faça sondagem do solo antes de definir a fundação" },
      { id: "cs39", title: 'Não escolha fundação simplesmente porque "todo mundo na região faz assim"', description: "Fundação deve considerar solo, cargas e projeto." },
      { id: "cs40", title: "Contrate arquiteto e/ou engenheiro habilitado e exija ART/RRT dos serviços correspondentes" },
      { id: "cs41", title: "Defina um orçamento máximo real antes de começar o projeto" },
      { id: "cs42", title: "Separe uma reserva para imprevistos", description: "Construções quase sempre apresentam gastos não previstos." },
      { id: "cs43", title: "Não faça uma casa no limite absoluto do orçamento esperando que nada dê errado" },
      { id: "cs44", title: "Antes de desenhar cômodos, escreva como sua família realmente vive" },
    ],
  },
  {
    id: "rotina",
    title: "Pense na rotina, não apenas na planta bonita",
    subtitle: "Perguntas simples que reduzem atritos repetidos todos os dias.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs45", title: "Onde entram as compras?" },
      { id: "cs46", title: "Onde ficam sapatos e bolsas quando alguém chega?" },
      { id: "cs47", title: "Onde ficam vassoura, aspirador, ferramentas e produtos de limpeza?" },
      { id: "cs48", title: "Onde fica o lixo até a coleta?" },
      { id: "cs49", title: "Onde as roupas serão lavadas?" },
      { id: "cs50", title: "Onde serão secas?" },
      { id: "cs51", title: "Onde ficará a roupa suja?" },
      { id: "cs52", title: "Onde ficará a despensa?" },
      { id: "cs53", title: "Onde guardar malas e objetos pouco utilizados?" },
      { id: "cs54", title: "Onde receber entregadores sem precisar abrir completamente a casa?" },
      { id: "cs55", title: "Onde ficarão bicicletas?" },
      { id: "cs56", title: "Onde ficarão equipamentos de internet?" },
      { id: "cs57", title: "Onde trabalhar em home office?" },
      { id: "cs58", title: "Onde ficarão condensadoras de ar-condicionado?" },
      { id: "cs59", title: "Onde ficará a caixa-d'água e como será feito o acesso para manutenção?" },
      { id: "cs60", title: "Onde ficarão registros hidráulicos?" },
      { id: "cs61", title: "Onde ficará o quadro elétrico?" },
      { id: "cs62", title: "Como um técnico chegará até esses equipamentos daqui a dez anos?" },
    ],
  },
  {
    id: "dimensionamento",
    title: "Dimensionamento",
    subtitle: "Móveis e equipamentos em escala real antes de aprovar a planta.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs63", title: "Desenhe os ambientes com móveis em escala real" },
      { id: "cs64", title: "Coloque cama, sofá, televisão, mesa, geladeira, armários e eletrodomésticos na planta antes de aprová-la" },
      { id: "cs65", title: "Simule a abertura das portas" },
      { id: "cs66", title: "Simule a abertura de geladeira, forno, lava-louças, armários e gavetas" },
      { id: "cs67", title: "Veja se é possível circular enquanto outra pessoa utiliza esses equipamentos" },
      { id: "cs68", title: "Confira se móveis grandes conseguirão entrar na casa depois de pronta" },
      { id: "cs69", title: "Não economize centímetros justamente nos locais de circulação" },
      { id: "cs70", title: "Pense onde ficarão tomadas antes de definir o layout definitivo" },
    ],
  },
  {
    id: "casa-daqui-20-anos",
    title: "Pense na casa daqui a 20 anos",
    subtitle: "Acessibilidade e flexibilidade para o futuro da família.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs71", title: "Evite desníveis desnecessários" },
      { id: "cs72", title: "Pense na possibilidade de moradores idosos ou pessoas com mobilidade reduzida" },
      { id: "cs73", title: "Se houver sobrado, avalie se existe ao menos alguma possibilidade de dormitório e banheiro utilizáveis no térreo" },
      { id: "cs74", title: "Dimensione corredores e portas pensando também em acessibilidade" },
      { id: "cs75", title: "Evite projetos que dependam de escadas para absolutamente todas as atividades importantes" },
      { id: "cs76", title: "Pense se a casa consegue se adaptar a mudanças familiares sem uma reforma gigantesca" },
    ],
  },
  {
    id: "projeto-hidraulico",
    title: "Projeto hidráulico",
    subtitle: "Reservatórios, registros, água quente/fria e esgoto.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs77", title: "Defina corretamente reservatórios e capacidade da caixa-d'água" },
      { id: "cs78", title: "Pense na facilidade de acesso para limpeza e manutenção" },
      { id: "cs79", title: "Planeje registros setorizados", description: "Não deveria ser necessário cortar a água da casa inteira para trocar uma torneira." },
      { id: "cs80", title: "Planeje corretamente água quente e fria" },
      { id: "cs81", title: "Se pretende usar aquecimento a gás, solar ou boiler, decida isso ainda na fase de projeto" },
      { id: "cs82", title: "Pense em pontos futuros mesmo que o equipamento não seja instalado imediatamente" },
      { id: "cs83", title: "Evite trajetos hidráulicos desnecessariamente longos" },
      { id: "cs84", title: "Planeje corretamente ventilação da rede de esgoto" },
      { id: "cs85", title: "Preste muita atenção às inclinações das tubulações de esgoto" },
      { id: "cs86", title: "Planeje pontos externos de água para jardim, garagem e limpeza" },
      { id: "cs87", title: "Pense onde ficará uma eventual bomba e como será feita sua manutenção" },
    ],
  },
  {
    id: "projeto-eletrico",
    title: "Projeto elétrico",
    subtitle: "Muito mais do que colocar tomadas na planta.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs88", title: 'Não trate projeto elétrico como "colocar tomadas na planta"' },
      { id: "cs89", title: "Planeje circuitos independentes para equipamentos de grande potência" },
      { id: "cs90", title: "Dimensione corretamente chuveiros, forno, cooktop, ar-condicionado e outros equipamentos" },
      { id: "cs91", title: "Preveja DR, DPS e aterramento adequados" },
      { id: "cs92", title: "Pense onde você realmente precisará de tomadas" },
      { id: "cs93", title: "Coloque tomadas considerando o layout dos móveis" },
      { id: "cs94", title: "Pense em tomadas externas" },
      { id: "cs95", title: "Pense em tomadas para aspirador" },
      { id: "cs96", title: "Pense em pontos para televisão" },
      { id: "cs97", title: "Pense em pontos para câmeras" },
      { id: "cs98", title: "Pense em automatização de portão" },
      { id: "cs99", title: "Pense em carregamento de carro elétrico, mesmo que você não tenha um hoje" },
      { id: "cs100", title: "Pense em futura instalação de energia solar" },
      { id: "cs101", title: "Se houver possibilidade, deixe infraestrutura preparada para futuras ampliações", description: "É muito mais barato deixar eletroduto, conduíte e infraestrutura vazios durante a construção do que quebrar paredes depois." },
    ],
  },
  {
    id: "internet-rede",
    title: "Internet e rede",
    subtitle: "Fibra, roteador, cabeamento e pontos de acesso.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs102", title: "Defina onde entrará a fibra da operadora" },
      { id: "cs103", title: "Crie um local adequado para modem, roteador, switch e outros equipamentos" },
      { id: "cs104", title: "Considere passar cabo de rede para escritório, televisões e pontos estratégicos" },
      { id: "cs105", title: "Em casas grandes ou com mais de um pavimento, planeje pontos para access points" },
      { id: "cs106", title: "Evite colocar toda a infraestrutura de internet dentro de um armário metálico ou em um canto péssimo para distribuição do Wi-Fi" },
      { id: "cs107", title: "Passe conduítes extras enquanto as paredes ainda estão abertas" },
    ],
  },
  {
    id: "ar-condicionado",
    title: "Ar-condicionado",
    subtitle: "Infraestrutura pronta mesmo sem instalar de imediato.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs108", title: "Mesmo que não pretenda instalar imediatamente, considere deixar infraestrutura pronta" },
      { id: "cs109", title: "Defina previamente a posição das evaporadoras" },
      { id: "cs110", title: "Defina onde ficarão as condensadoras" },
      { id: "cs111", title: "Pense na drenagem da água de condensação" },
      { id: "cs112", title: "Planeje alimentação elétrica adequada" },
      { id: "cs113", title: "Evite condensadoras em locais impossíveis ou perigosos de acessar para manutenção" },
    ],
  },
  {
    id: "impermeabilizacao",
    title: "Impermeabilização",
    subtitle: "Não economize no que ficará escondido depois.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs114", title: "Não economize justamente naquilo que ficará escondido depois" },
      { id: "cs115", title: "Impermeabilização ruim pode custar muito mais para corrigir do que para executar corretamente" },
      { id: "cs116", title: "Dê atenção especial a banheiros, áreas externas, lajes, sacadas, floreiras, paredes em contato com solo e fundações" },
      { id: "cs117", title: "Faça os testes necessários antes de colocar revestimento por cima" },
      { id: "cs118", title: "Fotografe as etapas de impermeabilização antes de tudo ser coberto" },
    ],
  },
  {
    id: "drenagem-terreno",
    title: "Drenagem do terreno",
    subtitle: "Para onde vai a água da chuva antes, durante e depois da obra.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs119", title: "Defina para onde irá a água da chuva antes de construir" },
      { id: "cs120", title: "Calcule corretamente calhas e condutores" },
      { id: "cs121", title: "Evite jogar água do telhado simplesmente no pé da fundação" },
      { id: "cs122", title: "Planeje ralos externos" },
      { id: "cs123", title: "Mantenha os caimentos corretos dos pisos externos" },
      { id: "cs124", title: "Garanta que quintal e garagem não conduzam água para dentro da casa" },
      { id: "cs125", title: "Preserve as áreas permeáveis exigidas e aproveite-as no projeto de drenagem" },
      { id: "cs126", title: "Considere soluções de retenção/infiltração quando adequadas e permitidas" },
    ],
  },
  {
    id: "telhado-cobertura",
    title: "Telhado e cobertura",
    subtitle: "Escolha pensando em manutenção, não só em estética.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs127", title: "Não escolha telhado apenas pela estética" },
      { id: "cs128", title: "Considere manutenção futura" },
      { id: "cs129", title: "Planeje acesso seguro ao telhado" },
      { id: "cs130", title: "Dimensione corretamente calhas e condutores" },
      { id: "cs131", title: "Dê atenção especial aos rufos" },
      { id: "cs132", title: "Pense no isolamento térmico da cobertura" },
      { id: "cs133", title: "Se pretende instalar painéis solares, considere isso no projeto estrutural e na orientação da cobertura" },
      { id: "cs134", title: "Evite criar locais onde folhas e sujeira inevitavelmente ficarão acumuladas" },
    ],
  },
  {
    id: "durante-obra",
    title: "Durante a obra",
    subtitle: "Acompanhamento, registro e fotos que valem ouro no futuro.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs135", title: "Tenha projeto executivo suficientemente detalhado antes de começar" },
      { id: "cs136", title: "Evite decidir tudo diretamente com o pedreiro durante a execução" },
      { id: "cs137", title: "Toda alteração relevante deve ser registrada" },
      { id: "cs138", title: "Faça acompanhamento técnico periódico" },
      { id: "cs139", title: "Fotografe todas as etapas da obra" },
      { id: "cs140", title: "Fotografe especialmente instalações antes de serem escondidas" },
      { id: "cs141", title: "Antes de rebocar/fechar paredes, fotografe onde passam tubos e conduítes" },
      { id: "cs142", title: "Coloque uma trena ou alguma referência de medida nas fotos quando necessário" },
      { id: "cs143", title: "Organize as fotos por cômodo e data" },
      { id: "cs144", title: "Guarde projetos e versões finais" },
      { id: "cs145", title: "Guarde notas fiscais e especificações de materiais importantes" },
      { id: "cs146", title: "Registre marca/modelo de itens que poderão precisar de reposição no futuro", description: "Essas fotos podem valer ouro daqui a dez anos quando alguém precisar furar uma parede e você quiser saber exatamente onde passa um cano." },
    ],
  },
  {
    id: "antes-concretar",
    title: "Antes de concretar",
    subtitle: "Últimas conferências antes de uma etapa impossível de desfazer.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs147", title: "Confira medidas" },
      { id: "cs148", title: "Confira níveis" },
      { id: "cs149", title: "Confira posição de pilares e elementos estruturais" },
      { id: "cs150", title: "Confira passagens previstas para instalações" },
      { id: "cs151", title: "Não permita alterações improvisadas em elementos estruturais sem aprovação do responsável técnico" },
    ],
  },
  {
    id: "antes-fechar-paredes",
    title: "Antes de fechar paredes e forros",
    subtitle: "Fotografe e teste tudo antes de esconder as instalações.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs152", title: "Fotografe instalações hidráulicas" },
      { id: "cs153", title: "Fotografe instalações elétricas" },
      { id: "cs154", title: "Fotografe tubulações de ar-condicionado" },
      { id: "cs155", title: "Fotografe conduítes de internet" },
      { id: "cs156", title: "Teste a hidráulica" },
      { id: "cs157", title: "Confira a elétrica" },
      { id: "cs158", title: "Confira pontos de iluminação" },
      { id: "cs159", title: "Confira tomadas" },
      { id: "cs160", title: "Confira pontos de rede" },
      { id: "cs161", title: "Confira drenos" },
      { id: "cs162", title: "Confira se ficou alguma infraestrutura futura planejada" },
    ],
  },
  {
    id: "antes-revestimentos",
    title: "Antes de colocar revestimentos",
    subtitle: "Testes e conferências antes do assentamento.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs163", title: "Teste impermeabilizações" },
      { id: "cs164", title: "Confira caimentos de banheiros e áreas externas" },
      { id: "cs165", title: "Veja se a água realmente vai para os ralos" },
      { id: "cs166", title: "Confira esquadro e nivelamento" },
      { id: "cs167", title: "Defina paginação dos revestimentos antes do assentamento" },
    ],
  },
  {
    id: "antes-receber-casa",
    title: "Antes de receber a casa",
    subtitle: "O checklist de entrega da obra.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs168", title: "Teste todas as tomadas" },
      { id: "cs169", title: "Teste iluminação" },
      { id: "cs170", title: "Teste DR e demais dispositivos de proteção conforme orientação técnica" },
      { id: "cs171", title: "Abra várias torneiras simultaneamente" },
      { id: "cs172", title: "Teste chuveiros" },
      { id: "cs173", title: "Dê descarga" },
      { id: "cs174", title: "Teste todos os registros" },
      { id: "cs175", title: "Procure vazamentos" },
      { id: "cs176", title: "Veja se existe retorno de cheiro pelos ralos" },
      { id: "cs177", title: "Jogue água nas áreas molhadas e externas e observe os caimentos" },
      { id: "cs178", title: "Teste portas e janelas" },
      { id: "cs179", title: "Procure infiltração nas esquadrias" },
      { id: "cs180", title: "Procure pisos ocos" },
      { id: "cs181", title: "Confira rejuntes" },
      { id: "cs182", title: "Confira pintura" },
      { id: "cs183", title: "Confira telhado, rufos e calhas" },
      { id: "cs184", title: "Teste portão" },
      { id: "cs185", title: "Teste interfone" },
      { id: "cs186", title: "Teste internet/rede" },
      { id: "cs187", title: "Confira todos os itens contratados antes de considerar a obra encerrada" },
    ],
  },
  {
    id: "guarde-para-sempre",
    title: "Guarde para sempre",
    subtitle: "Monte a pasta física e digital da casa.",
    appliesTo: "house",
    category: "construcao",
    items: [
      { id: "cs188", title: "Projeto arquitetônico final" },
      { id: "cs189", title: "Projeto estrutural" },
      { id: "cs190", title: "Projeto elétrico" },
      { id: "cs191", title: "Projeto hidráulico" },
      { id: "cs192", title: "Projetos complementares" },
      { id: "cs193", title: "Levantamento topográfico" },
      { id: "cs194", title: "Sondagem, quando realizada" },
      { id: "cs195", title: "ARTs/RRTs" },
      { id: "cs196", title: "Aprovações e documentos municipais" },
      { id: "cs197", title: "Notas fiscais importantes" },
      { id: "cs198", title: "Manuais" },
      { id: "cs199", title: "Garantias" },
      { id: "cs200", title: "Especificações de tintas e revestimentos" },
      { id: "cs201", title: "Fotos das instalações antes do fechamento das paredes" },
      { id: "cs202", title: "Localização de registros" },
      { id: "cs203", title: "Localização de caixas de passagem" },
      { id: "cs204", title: "Informações sobre impermeabilização" },
      { id: "cs205", title: "Documentação da obra", description: "A casa pronta esconde justamente as informações que você mais precisará quando surgir um problema." },
    ],
  },
];
